FROM node:14

RUN apt-get update && \
    apt-get install -y nginx vim

RUN npm install -g npm@latest
RUN npm install -g @angular/cli

COPY frontend /opt/app
WORKDIR /opt/app
RUN npm install
RUN ng build --configuration production

RUN mv /opt/app/dist /tmp/dist
RUN rm -rf /opt/app
RUN mv /tmp/dist /opt/app
