FROM node:14

RUN apt-get update && \
    apt-get install -y nginx vim

RUN npm install -g npm@latest
RUN npm install -g @angular/cli

COPY frontend /opt/app
WORKDIR /opt/app
RUN npm install
RUN ng build --configuration production

RUN mv /opt/app/dist /tmp/dist
RUN rm -rf /opt/app
RUN mv /tmp/dist /opt/app

RUN npm install -g pm2
ADD frontend/docker/process.yml /etc/app/process.yml
COPY nginx.conf /etc/nginx/sites-enables/default

CMD ["pm2-runtime", "/etc/app/process.yml"]
